* Integration test in Flutter

Flutter *integration test* is performed by the command ~flutter drive~; the test file
is the file in the ~--target=path_to_test.dart~. The test files are executed ON THE DEVICE,
AND COULD BE CALLED ON-DEVICE-TESTS.

Files in this directory which end with '_test.dart' are such *integration tests*, performed
in a command such as

#+begin_src: sh
  # Note: "$examplesDescriptors" may be "allSupported" or similar single test or named group of tests,
  #       or a list of single test names
  flutter drive \
    --dart-define=EXAMPLES_DESCRIPTORS="$examplesDescriptors" \
    --driver=test_driver/integration_test.dart  \
    --target=integration_test/screenshot_create_test.dart
#+end_src

Optionally, the *integration test* can be controlled, from the computer, by another program, which could be described as
'on-computer driver for the on-device integration test'.  Such 'on-computer driver' is the program
~--driver=test_driver/integration_test.dart~ program above; it runs on the computer,
and controls the program in the ~--target=integration_test/screenshot_create_test.dart~ running on the device (drive).

Note: The naming of the on-device integration test TARGET and it's on-computer controlling program DRIVER
      seems backwards, but Flutter seems to insist on it, by making the name 'integration_test.dart' for the DRIVER
      the default required name.

See the "Testing in Flutter" heading in https://github.com/mzimmerm/flutter_experiments/blob/master/doc/flutter-notes.org
for details of Dart unit test, Flutter widget test and Flutter integration test.

See https://docs.flutter.dev/cookbook/testing/integration/introduction
  for integration testing in Flutter.

See https://dev.to/mjablecnik/take-screenshot-during-flutter-integration-tests-435k
  for how to take a screenshot from your Flutter app inside flutter test integration_test/app_test.dart;
  but the same should work from an actual flutter run --device_id app.dart

